"use strict";

/* Reregulation Provider Registry — read-only analyst viewer.
 * Loads viz/data/bundle.json (generated by scripts/export_viz.py from
 * data/release/*.parquet) and renders everything client-side. No build step,
 * no external requests once bundle.json + vendored assets are local. */

const RAMP = ["#eef3f8", "#cfe0ee", "#a3c3dd", "#6f9dc4", "#3f74a3", "#1f4a75"];
const STATUS_ORDER = ["active", "exited", "suspended", "unknown"];

let DATA = null;
let idx = {}; // derived indices, built once after load
let filters = { jurisdiction: null, program_id: null, provider_type: null, program_type: null, current_status: null, search: "" };
let sort = { key: "legal_name", dir: 1 };
let expandedProviderId = null;
let detailProgramId = null;

fetch("data/bundle.json")
  .then((r) => {
    if (!r.ok) throw new Error("bundle.json fetch failed: " + r.status);
    return r.json();
  })
  .then((bundle) => {
    DATA = bundle;
    buildIndices();
    mountShell();
    renderAll();
  })
  .catch((err) => {
    document.getElementById("app").innerHTML =
      '<p style="padding:40px 0;color:#a13d2f">Could not load viz/data/bundle.json — run <code>make viz</code> (or <code>uv run python scripts/export_viz.py</code>) first. (' +
      err.message +
      ")</p>";
  });

function buildIndices() {
  idx.programById = new Map(DATA.programs.map((p) => [p.program_id, p]));
  idx.snapshotById = new Map(DATA.snapshots.map((s) => [s.snapshot_id, s]));
  idx.expectedZeroByProgram = new Map(DATA.expected_zero.map((z) => [z.program_id, z.reason]));

  idx.eventsByProvider = new Map();
  for (const e of DATA.events) {
    if (!idx.eventsByProvider.has(e.provider_id)) idx.eventsByProvider.set(e.provider_id, []);
    idx.eventsByProvider.get(e.provider_id).push(e);
  }
  for (const arr of idx.eventsByProvider.values()) arr.sort((a, b) => (a.event_date < b.event_date ? -1 : 1));

  // provider_id -> program_id, for joining events to a program's timeline
  idx.providerProgram = new Map(DATA.providers.map((p) => [p.provider_id, p.program_id]));

  idx.eventsByProgram = new Map();
  for (const e of DATA.events) {
    const pid = idx.providerProgram.get(e.provider_id);
    if (!pid) continue;
    if (!idx.eventsByProgram.has(pid)) idx.eventsByProgram.set(pid, []);
    idx.eventsByProgram.get(pid).push(e);
  }
  for (const arr of idx.eventsByProgram.values()) arr.sort((a, b) => (a.event_date < b.event_date ? -1 : 1));

  // jurisdiction -> { programs: [...], totalProviders, allZero }
  idx.jurisdictionInfo = new Map();
  for (const prog of DATA.programs) {
    const j = prog.jurisdiction;
    if (!idx.jurisdictionInfo.has(j)) idx.jurisdictionInfo.set(j, { programs: [], totalProviders: 0 });
    const info = idx.jurisdictionInfo.get(j);
    info.programs.push(prog);
    info.totalProviders += prog.provider_count;
  }
  for (const info of idx.jurisdictionInfo.values()) {
    info.allZero = info.programs.every((p) => p.provider_count === 0);
  }

  idx.maxJurisdictionProviders = Math.max(...[...idx.jurisdictionInfo.values()].map((i) => i.totalProviders), 1);
}

function mountShell() {
  const tpl = document.getElementById("tpl-main");
  document.getElementById("app").replaceWith(tpl.content.cloneNode(true));
  wireStaticControls();
}

// ── filter helpers ───────────────────────────────────────────────────────

function toggleFilter(key, value) {
  filters[key] = filters[key] === value ? null : value;
  renderAll();
}

function setFilter(key, value) {
  filters[key] = value || null;
  renderAll();
}

function clearAllFilters() {
  filters = { jurisdiction: null, program_id: null, provider_type: null, program_type: null, current_status: null, search: "" };
  document.getElementById("search-box").value = "";
  renderAll();
}

function filteredProviders() {
  const q = filters.search.trim().toLowerCase();
  return DATA.providers.filter((p) => {
    if (filters.jurisdiction && p.jurisdiction !== filters.jurisdiction) return false;
    if (filters.program_id && p.program_id !== filters.program_id) return false;
    if (filters.provider_type && p.provider_type !== filters.provider_type) return false;
    if (filters.current_status && p.current_status !== filters.current_status) return false;
    if (filters.program_type) {
      const prog = idx.programById.get(p.program_id);
      if (!prog || prog.program_type !== filters.program_type) return false;
    }
    if (q) {
      const hay = (p.legal_name + " " + p.normalized_name + " " + (p.website || "")).toLowerCase();
      if (!hay.includes(q)) return false;
    }
    return true;
  });
}

// ── top-level render ─────────────────────────────────────────────────────

function renderAll() {
  renderStatStrip();
  renderChips();
  renderMap();
  renderBars();
  renderExpectedZeroNote();
  renderMultiples();
  renderProgramPanel();
  renderTable();
  syncToolbarControls();
}

function renderStatStrip() {
  const c = DATA.counts;
  document.getElementById("stat-strip").innerHTML =
    `<span><b>${c.programs}</b>programs</span>` +
    `<span><b>${c.states}</b>states</span>` +
    `<span><b>${c.providers}</b>providers</span>` +
    `<span><b>${c.events}</b>events</span>` +
    `<span><b>${c.snapshots}</b>snapshots</span>`;
  document.getElementById("gen-at").textContent = new Date(DATA.generated_at).toISOString().slice(0, 16).replace("T", " ") + " UTC";
}

function renderChips() {
  const labels = {
    jurisdiction: "Jurisdiction",
    program_id: "Program",
    provider_type: "Provider type",
    program_type: "Program type",
    current_status: "Status",
  };
  const chips = [];
  for (const key of Object.keys(labels)) {
    if (!filters[key]) continue;
    let val = filters[key];
    if (key === "program_id") val = idx.programById.get(val)?.program_name || val;
    chips.push(`<span class="chip">${labels[key]}: ${escapeHtml(val)}<button data-clear="${key}">×</button></span>`);
  }
  if (filters.search) {
    chips.push(`<span class="chip">Search: "${escapeHtml(filters.search)}"<button data-clear="search">×</button></span>`);
  }
  document.getElementById("filter-chips").innerHTML = chips.join(" ");
  document.getElementById("clear-all").style.display = chips.length ? "inline" : "none";
  document.querySelectorAll("#filter-chips button[data-clear]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const k = btn.dataset.clear;
      if (k === "search") {
        filters.search = "";
        document.getElementById("search-box").value = "";
      } else {
        filters[k] = null;
      }
      renderAll();
    });
  });
}

// ── choropleth map ───────────────────────────────────────────────────────

function rampColor(t) {
  t = Math.max(0, Math.min(1, t));
  const n = RAMP.length - 1;
  const i = Math.min(n - 1, Math.floor(t * n));
  const localT = t * n - i;
  return lerpHex(RAMP[i], RAMP[i + 1], localT);
}
function lerpHex(a, b, t) {
  const pa = hexToRgb(a), pb = hexToRgb(b);
  const r = Math.round(pa[0] + (pb[0] - pa[0]) * t);
  const g = Math.round(pa[1] + (pb[1] - pa[1]) * t);
  const bl = Math.round(pa[2] + (pb[2] - pa[2]) * t);
  return `rgb(${r},${g},${bl})`;
}
function hexToRgb(h) {
  const v = parseInt(h.slice(1), 16);
  return [(v >> 16) & 255, (v >> 8) & 255, v & 255];
}

function renderMap() {
  const svg = document.getElementById("map-svg");
  svg.setAttribute("viewBox", DATA.map.viewBox);
  const tooltip = document.getElementById("map-tooltip");

  let defs = "<defs><pattern id='hatch' width='6' height='6' patternTransform='rotate(45)' patternUnits='userSpaceOnUse'>" +
    "<rect width='6' height='6' fill='#eaf1f9'></rect>" +
    "<line x1='0' y1='0' x2='0' y2='6' stroke='#9db8d4' stroke-width='2'></line>" +
    "</pattern></defs>";

  let body = "";
  for (const [usps, d] of Object.entries(DATA.map.states)) {
    const info = idx.jurisdictionInfo.get(usps);
    let fill, hasProgram = !!info;
    if (!info) {
      fill = "var(--none-fill)";
    } else if (info.allZero) {
      fill = "url(#hatch)";
    } else {
      fill = rampColor(info.totalProviders / idx.maxJurisdictionProviders);
    }
    const classes = ["state"];
    if (!hasProgram) classes.push("no-program");
    if (filters.jurisdiction && filters.jurisdiction !== usps) classes.push("dimmed");
    if (filters.jurisdiction === usps) classes.push("selected");
    body += `<path class="${classes.join(" ")}" data-usps="${usps}" d="${d}" fill="${fill}" fill-rule="evenodd"></path>`;
  }
  svg.innerHTML = defs + body;

  svg.querySelectorAll("path.state").forEach((path) => {
    const usps = path.dataset.usps;
    const info = idx.jurisdictionInfo.get(usps);
    path.addEventListener("mousemove", (ev) => {
      tooltip.style.display = "block";
      tooltip.style.left = ev.clientX + 14 + "px";
      tooltip.style.top = ev.clientY + 14 + "px";
      if (!info) {
        tooltip.innerHTML = `<b>${usps}</b><br>No reregulation program in scope for v1.`;
      } else {
        let html = `<b>${usps}</b><br>${info.totalProviders} provider${info.totalProviders === 1 ? "" : "s"}`;
        for (const prog of info.programs) {
          html += `<br>${escapeHtml(prog.program_name)}: ${prog.provider_count}`;
          if (prog.provider_count === 0) html += " — documented zero";
        }
        tooltip.innerHTML = html;
      }
    });
    path.addEventListener("mouseleave", () => (tooltip.style.display = "none"));
    if (info) {
      path.addEventListener("click", () => toggleFilter("jurisdiction", usps));
    }
  });

  document.getElementById("legend-ramp").innerHTML = RAMP.map((c) => `<span style="background:${c}"></span>`).join("");
}

// ── bar charts ───────────────────────────────────────────────────────────

function renderBars() {
  const typeCounts = new Map();
  const statusCounts = new Map();
  for (const p of DATA.providers) {
    const prog = idx.programById.get(p.program_id);
    const t = prog ? prog.program_type : "unknown";
    typeCounts.set(t, (typeCounts.get(t) || 0) + 1);
    statusCounts.set(p.current_status, (statusCounts.get(p.current_status) || 0) + 1);
  }
  renderBarGroup("bars-type", typeCounts, "program_type");
  renderBarGroup(
    "bars-status",
    new Map(STATUS_ORDER.map((s) => [s, statusCounts.get(s) || 0])),
    "current_status"
  );
}

function renderBarGroup(elId, counts, filterKey) {
  const max = Math.max(...counts.values(), 1);
  const rows = [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([label, n]) => {
      const selected = filters[filterKey] === label;
      const pct = (n / max) * 100;
      return `<div class="bar-row${selected ? " selected" : ""}" data-val="${escapeHtml(label)}">
        <span class="bar-label" title="${escapeHtml(label)}">${escapeHtml(label)}</span>
        <span class="bar-track"><span class="bar-fill" style="width:${pct}%"></span></span>
        <span class="bar-n num">${n}</span>
      </div>`;
    })
    .join("");
  const el = document.getElementById(elId);
  el.innerHTML = rows;
  el.querySelectorAll(".bar-row").forEach((row) => {
    row.addEventListener("click", () => toggleFilter(filterKey, row.dataset.val));
  });
}

function renderExpectedZeroNote() {
  const items = DATA.expected_zero
    .map((z) => {
      const prog = idx.programById.get(z.program_id);
      return `<li><b>${escapeHtml(prog ? prog.program_name : z.program_id)}</b> (${prog.jurisdiction}) — ${escapeHtml(z.reason)}</li>`;
    })
    .join("");
  document.getElementById("expected-zero-note").innerHTML =
    `<b>${DATA.expected_zero.length} program${DATA.expected_zero.length === 1 ? "" : "s"} above show 0 providers by design</b>, not by scraper failure — each has a snapshotted evidentiary source page documenting why:<ul>${items}</ul>`;
}

// ── longitudinal small multiples ─────────────────────────────────────────

function programTimeSeries(program_id) {
  const events = idx.eventsByProgram.get(program_id) || [];
  const byDate = new Map();
  for (const e of events) {
    if (!byDate.has(e.event_date)) byDate.set(e.event_date, 0);
    if (e.event_type === "authorized") byDate.set(e.event_date, byDate.get(e.event_date) + 1);
    if (e.event_type === "disappeared_from_roster") byDate.set(e.event_date, byDate.get(e.event_date) - 1);
  }
  const dates = [...byDate.keys()].sort();
  let net = 0;
  const points = dates.map((d) => {
    net += byDate.get(d);
    return { date: d, net };
  });
  return points;
}

function renderMultiples() {
  const grid = document.getElementById("multiples-grid");
  grid.innerHTML = DATA.programs
    .map((prog) => {
      const points = programTimeSeries(prog.program_id);
      const nSnaps = points.length;
      const dimmed = filters.jurisdiction && filters.jurisdiction !== prog.jurisdiction;
      const selected = filters.program_id === prog.program_id;
      const w = 200, h = 54, pad = 4;
      let svgInner;
      if (nSnaps <= 1) {
        const y = h / 2;
        svgInner = `<path class="trend flat" d="M${pad},${y} L${w - pad},${y}"></path>` +
          `<circle class="endpoint" cx="${w - pad}" cy="${y}" r="2.2"></circle>`;
      } else {
        const maxN = Math.max(...points.map((p) => p.net), 1);
        const minN = Math.min(...points.map((p) => p.net), 0);
        const range = Math.max(maxN - minN, 1);
        const xStep = (w - 2 * pad) / (points.length - 1);
        const xy = points.map((p, i) => [pad + i * xStep, h - pad - ((p.net - minN) / range) * (h - 2 * pad)]);
        const d = xy.map((pt, i) => (i === 0 ? "M" : "L") + pt[0].toFixed(1) + "," + pt[1].toFixed(1)).join(" ");
        const last = xy[xy.length - 1];
        svgInner = `<path class="trend" d="${d}"></path><circle class="endpoint" cx="${last[0]}" cy="${last[1]}" r="2.2"></circle>`;
      }
      return `<div class="multiple${dimmed ? " dimmed" : ""}${selected ? " selected" : ""}" data-pid="${prog.program_id}" style="${dimmed ? "opacity:.4" : ""}">
        <div class="m-head"><span class="m-name">${escapeHtml(shortName(prog))}</span><span class="m-n">${prog.provider_count}</span></div>
        <svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">${svgInner}</svg>
        <div class="m-flat-note">${nSnaps <= 1 ? "1 snapshot — no trend yet" : nSnaps + " snapshots"}</div>
      </div>`;
    })
    .join("");
  grid.querySelectorAll(".multiple").forEach((el) => {
    el.addEventListener("click", () => {
      const pid = el.dataset.pid;
      filters.program_id = filters.program_id === pid ? null : pid;
      detailProgramId = filters.program_id ? pid : null;
      renderAll();
      if (detailProgramId) document.getElementById("program-panel").scrollIntoView({ behavior: "smooth", block: "center" });
    });
  });
}

function shortName(prog) {
  return prog.program_name.replace("Program", "").replace("  ", " ").trim();
}

// ── program detail panel ─────────────────────────────────────────────────

function renderProgramPanel() {
  const sec = document.getElementById("sec-program-detail");
  const pid = filters.program_id;
  if (!pid || !idx.programById.has(pid)) {
    sec.style.display = "none";
    return;
  }
  sec.style.display = "block";
  const prog = idx.programById.get(pid);
  const zeroReason = idx.expectedZeroByProgram.get(pid);
  const providers = DATA.providers.filter((p) => p.program_id === pid);
  const statusBreakdown = new Map();
  for (const p of providers) statusBreakdown.set(p.current_status, (statusBreakdown.get(p.current_status) || 0) + 1);
  const snapshots = DATA.snapshots.filter((s) => s.program_id === pid).sort((a, b) => (a.retrieved_at < b.retrieved_at ? -1 : 1));

  const flags = [
    ["Non-lawyer ownership", prog.allows_nonlawyer_ownership],
    ["UPL waiver", prog.allows_upl_waiver],
    ["Software provider eligible", prog.allows_software_provider],
  ]
    .map(([label, on]) => `<span class="flag${on ? " on" : ""}"><span class="dot"></span>${label}</span>`)
    .join("");

  const statusHtml = [...statusBreakdown.entries()]
    .map(([s, n]) => `<div>${n} <span style="color:var(--ink-soft)">${s}</span></div>`)
    .join("");

  const snapHtml =
    snapshots
      .map(
        (s) =>
          `<div class="snapshot-row"><a href="${s.source_url}" target="_blank" rel="noopener">${s.retrieved_at.slice(0, 10)}</a> · ${s.media_type} · <span class="mono">${s.content_sha256.slice(0, 12)}…</span></div>`
      )
      .join("") || '<div class="snapshot-row">none</div>';

  document.getElementById("program-panel").innerHTML = `
    <div class="pp-head">
      <div>
        <h3>${escapeHtml(prog.program_name)}${zeroReason ? '<span class="zero-badge">documented zero</span>' : ""}</h3>
        <div class="pp-meta">${prog.jurisdiction} · ${prog.program_type} · ${prog.regulator} · status: ${prog.program_status}${prog.sunset_date ? " · sunset " + prog.sunset_date : ""}</div>
        <div class="pp-meta">${escapeHtml(prog.authorizing_rule)}</div>
      </div>
      <button class="pp-close" id="pp-close">close</button>
    </div>
    <div class="flag-row">${flags}</div>
    ${zeroReason ? `<div class="expected-zero-note" style="margin:0 0 16px">${escapeHtml(zeroReason)}</div>` : ""}
    <div class="pp-cols">
      <div>
        <h4>Providers</h4>
        <div style="font-size:1.4rem;font-weight:600">${providers.length}</div>
        <div style="font-size:0.74rem;color:var(--ink-soft);margin-bottom:8px">total, by current_status:</div>
        ${statusHtml}
        <button class="pp-close" id="pp-view-providers" style="margin-top:10px">view in table below ↓</button>
      </div>
      <div>
        <h4>Source snapshots (${snapshots.length})</h4>
        ${snapHtml}
      </div>
      <div>
        <h4>Documentation</h4>
        <div class="citation">Regulator: <a href="${prog.regulator_url}" target="_blank" rel="noopener">${prog.regulator_url}</a></div>
        <div class="citation">Full coverage/accuracy reconciliation: <code>${prog.validation_log || "n/a"}</code></div>
        <div class="citation">Retrieved: ${prog.retrieved_at.slice(0, 10)} · scraper v${prog.scraper_version}</div>
      </div>
    </div>
  `;
  document.getElementById("pp-close").addEventListener("click", () => {
    filters.program_id = null;
    renderAll();
  });
  document.getElementById("pp-view-providers").addEventListener("click", () => {
    document.getElementById("sec-table").scrollIntoView({ behavior: "smooth" });
  });
}

// ── provider table ───────────────────────────────────────────────────────

function renderTable() {
  const rows = filteredProviders();
  const cmp = sortComparator(sort.key, sort.dir);
  rows.sort(cmp);

  document.getElementById("result-count").textContent = `${rows.length} of ${DATA.providers.length} providers`;
  document.getElementById("table-sec-note").textContent = `(${DATA.providers.length} rows — click any row for full provenance)`;

  const tbody = document.getElementById("provider-tbody");
  tbody.innerHTML = rows
    .map((p) => {
      const prog = idx.programById.get(p.program_id);
      const areas = (p.practice_areas_raw && p.practice_areas_raw.length) ? p.practice_areas_raw.join(", ") : "—";
      const statusClass = p.current_status === "active" ? " active" : "";
      return `<tr data-pid="${p.provider_id}" class="${expandedProviderId === p.provider_id ? "expanded" : ""}">
        <td class="wrap">${escapeHtml(p.legal_name)}</td>
        <td>${escapeHtml(prog ? shortName(prog) : p.program_id)}</td>
        <td>${p.jurisdiction}</td>
        <td>${p.provider_type}</td>
        <td><span class="status-tag${statusClass}">${p.current_status}</span></td>
        <td class="num">${p.authorization_date || "—"}</td>
        <td class="wrap">${escapeHtml(areas)}</td>
      </tr>${expandedProviderId === p.provider_id ? detailRowHtml(p) : ""}`;
    })
    .join("");

  tbody.querySelectorAll("tr[data-pid]").forEach((tr) => {
    tr.addEventListener("click", () => {
      const pid = tr.dataset.pid;
      expandedProviderId = expandedProviderId === pid ? null : pid;
      renderTable();
    });
  });

  // header sort indicators + handlers (rebind once; header is static markup)
  document.querySelectorAll("#provider-table th[data-sort]").forEach((th) => {
    th.onclick = () => {
      const key = th.dataset.sort;
      sort.dir = sort.key === key ? -sort.dir : 1;
      sort.key = key;
      renderTable();
    };
    th.querySelector(".sort-arrow")?.remove();
    if (th.dataset.sort === sort.key) {
      th.innerHTML += `<span class="sort-arrow">${sort.dir === 1 ? "↑" : "↓"}</span>`;
    }
  });
}

function detailRowHtml(p) {
  const first = idx.snapshotById.get(p.first_seen_snapshot_id);
  const last = idx.snapshotById.get(p.last_seen_snapshot_id);
  const events = idx.eventsByProvider.get(p.provider_id) || [];
  const eventRows = events
    .map((e) => `<tr><td>${e.event_date}</td><td>${e.event_type}</td><td>${e.new_status}</td><td>${escapeHtml(e.detail || "—")}</td></tr>`)
    .join("");
  return `<tr class="detail-row"><td colspan="7">
    <div class="detail-grid">
      <div>
        <dt>Provider ID</dt><dd class="mono">${p.provider_id}</dd>
        <dt>Normalized name</dt><dd>${escapeHtml(p.normalized_name)}</dd>
        <dt>Website</dt><dd>${p.website ? `<a href="${p.website}" target="_blank" rel="noopener">${escapeHtml(p.website)}</a>` : "—"}</dd>
      </div>
      <div>
        <dt>Uses technology (self-reported)</dt><dd>${boolLabel(p.uses_technology)}</dd>
        <dt>Uses AI (self-reported)</dt><dd>${boolLabel(p.uses_ai)}</dd>
        <dt>Ownership structure</dt><dd>${p.ownership_structure ? escapeHtml(p.ownership_structure) : "—"}</dd>
      </div>
      <div>
        <dt>Source URL</dt><dd><a href="${p.source_url}" target="_blank" rel="noopener">${escapeHtml(p.source_url)}</a></dd>
        <dt>Retrieved / scraper</dt><dd>${p.retrieved_at.slice(0, 10)} · v${p.scraper_version}</dd>
        <dt>First → last seen snapshot</dt>
        <dd>${first ? first.retrieved_at.slice(0, 10) : "—"} → ${last ? last.retrieved_at.slice(0, 10) : "—"}</dd>
      </div>
    </div>
    <div class="event-history">
      <dt style="font-size:0.64rem;text-transform:uppercase;letter-spacing:.05em;color:var(--ink-faint)">Status event history (${events.length})</dt>
      <table><thead><tr><th>Date</th><th>Type</th><th>New status</th><th>Detail</th></tr></thead><tbody>${eventRows}</tbody></table>
    </div>
  </td></tr>`;
}

function boolLabel(v) {
  if (v === true) return "Yes";
  if (v === false) return "No";
  return "Unknown (NULL — not coded in v1)";
}

function sortComparator(key, dir) {
  return (a, b) => {
    let av = a[key], bv = b[key];
    if (key === "practice_areas_raw") {
      av = (av || []).join(", ");
      bv = (bv || []).join(", ");
    }
    if (av == null && bv == null) return 0;
    if (av == null) return 1; // nulls last regardless of direction
    if (bv == null) return -1;
    if (av < bv) return -1 * dir;
    if (av > bv) return 1 * dir;
    return 0;
  };
}

// ── toolbar wiring ───────────────────────────────────────────────────────

function wireStaticControls() {
  document.getElementById("clear-all").addEventListener("click", clearAllFilters);

  const jSel = document.getElementById("filter-jurisdiction");
  const juris = [...new Set(DATA.programs.map((p) => p.jurisdiction))].sort();
  for (const j of juris) jSel.innerHTML += `<option value="${j}">${j}</option>`;
  jSel.addEventListener("change", () => setFilter("jurisdiction", jSel.value));

  const pSel = document.getElementById("filter-program");
  for (const prog of [...DATA.programs].sort((a, b) => a.program_name.localeCompare(b.program_name))) {
    pSel.innerHTML += `<option value="${prog.program_id}">${escapeHtml(shortName(prog))} (${prog.provider_count})</option>`;
  }
  pSel.addEventListener("change", () => {
    filters.program_id = pSel.value || null;
    renderAll();
  });

  const tSel = document.getElementById("filter-type");
  for (const t of [...new Set(DATA.providers.map((p) => p.provider_type))].sort()) {
    tSel.innerHTML += `<option value="${t}">${t}</option>`;
  }
  tSel.addEventListener("change", () => setFilter("provider_type", tSel.value));

  const sSel = document.getElementById("filter-status");
  for (const s of STATUS_ORDER) sSel.innerHTML += `<option value="${s}">${s}</option>`;
  sSel.addEventListener("change", () => setFilter("current_status", sSel.value));

  const search = document.getElementById("search-box");
  let debounce;
  search.addEventListener("input", () => {
    clearTimeout(debounce);
    debounce = setTimeout(() => {
      filters.search = search.value;
      renderAll();
    }, 120);
  });
}

function syncToolbarControls() {
  document.getElementById("filter-jurisdiction").value = filters.jurisdiction || "";
  document.getElementById("filter-program").value = filters.program_id || "";
  document.getElementById("filter-type").value = filters.provider_type || "";
  document.getElementById("filter-status").value = filters.current_status || "";
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}
