"""Pydantic v2 models — these ARE the schema. Fail loudly on drift."""

from __future__ import annotations

import datetime
from dataclasses import dataclass
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, StringConstraints
from pydantic.functional_validators import AfterValidator

from models.enums import (
    AliasSource,
    CurrentStatus,
    EventType,
    MatchMethod,
    MediaType,
    ProgramStatus,
    ProgramType,
    ProviderType,
)

# ── annotated primitive types ─────────────────────────────────────────────────
#
# Define once here; import elsewhere.  Using Annotated + StringConstraints keeps
# validation declarative and composable without subclassing str.

NonEmptyStr = Annotated[str, StringConstraints(min_length=1, strip_whitespace=True)]

# USPS two-letter state/territory code, uppercase.
# Does not enforce against a closed list — territories (AS, GU, PR, VI …) are valid.
JurisdictionStr = Annotated[
    str,
    StringConstraints(pattern=r"^[A-Z]{2}$", strip_whitespace=True),
]

# SHA-256 hex digest: exactly 64 lowercase hex chars.
Sha256Str = Annotated[str, StringConstraints(pattern=r"^[0-9a-f]{64}$")]


def _require_http(v: str) -> str:
    if not v.startswith(("http://", "https://")):
        raise ValueError(f"must be an http/https URL, got {v!r}")
    return v


HttpUrlStr = Annotated[
    str,
    StringConstraints(min_length=1, strip_whitespace=True),
    AfterValidator(_require_http),
]


# ── base models ───────────────────────────────────────────────────────────────


class BaseRegistryModel(BaseModel):
    """Shared config for every model in this registry."""

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_default=True,
    )


class _Provenance(BaseRegistryModel):
    """Provenance fields required on every model derived from a scraped source.

    Golden rule 1: no field without a traceable origin.
    """

    source_url: HttpUrlStr
    retrieved_at: datetime.datetime
    scraper_version: NonEmptyStr


# ── §1.1  program ─────────────────────────────────────────────────────────────


class Program(_Provenance):
    """One row per reform program."""

    program_id: NonEmptyStr
    jurisdiction: JurisdictionStr
    program_name: NonEmptyStr
    program_type: ProgramType
    regulator: NonEmptyStr
    regulator_url: HttpUrlStr
    authorizing_rule: NonEmptyStr
    launch_date: datetime.date | None = None
    program_status: ProgramStatus
    sunset_date: datetime.date | None = None
    allows_nonlawyer_ownership: bool
    allows_upl_waiver: bool
    allows_software_provider: bool


# ── §1.2  provider ────────────────────────────────────────────────────────────


class Provider(_Provenance):
    """One row per authorized entity or individual.

    current_status is COMPUTED from provider_status_event on export — never
    set it by scraping a status field directly.
    """

    provider_id: NonEmptyStr
    program_id: NonEmptyStr
    provider_type: ProviderType
    legal_name: NonEmptyStr
    normalized_name: NonEmptyStr
    jurisdiction: JurisdictionStr
    authorization_date: datetime.date | None = None
    current_status: CurrentStatus = CurrentStatus.unknown
    practice_areas_raw: list[str] = Field(default_factory=list)
    practice_areas_list: list[str] | None = None
    ownership_structure: dict[str, Any] | None = None
    uses_technology: bool | None = None
    uses_ai: bool | None = None
    website: HttpUrlStr | None = None
    first_seen_snapshot_id: str | None = None
    last_seen_snapshot_id: str | None = None


# ── §1.3  provider_status_event ───────────────────────────────────────────────


class ProviderStatusEvent(_Provenance):
    """The longitudinal heart. Generated by diffing snapshots — never hand-edited.

    disappeared_from_roster != revoked: dropping off a roster is an observation,
    not a legal conclusion.  Keep them distinct; let analysts decide.
    """

    event_id: NonEmptyStr
    provider_id: NonEmptyStr
    event_date: datetime.date
    event_type: EventType
    new_status: CurrentStatus
    detail: str | None = None
    source_snapshot_id: NonEmptyStr


# ── §1.4  provider_alias ──────────────────────────────────────────────────────


class ProviderAlias(_Provenance):
    """DBA names, former names, brand names.  Seed early for entity resolution."""

    provider_id: NonEmptyStr
    alias_name: NonEmptyStr
    alias_source: AliasSource


# ── §1.5  source_snapshot ─────────────────────────────────────────────────────


class SourceSnapshot(BaseRegistryModel):
    """Immutable record of a raw capture.  This IS the provenance document."""

    snapshot_id: NonEmptyStr
    program_id: NonEmptyStr
    source_url: HttpUrlStr
    retrieved_at: datetime.datetime
    content_sha256: Sha256Str
    storage_path: NonEmptyStr
    media_type: MediaType
    scraper_version: NonEmptyStr


# ── diff helper (no circular import — both diff.py and db.py import from here) ──


@dataclass(frozen=True)
class ProviderRef:
    """Minimal provider summary for snapshot diffing.

    Satisfies the same duck-typing contract as Provider w.r.t. the two fields
    that diff_snapshots actually reads.  Returned by RegistryStore when
    reconstructing the previous snapshot's provider set from the DB.
    """

    provider_id: str
    current_status: CurrentStatus


# ── §1.6  crosswalk_courtlistener (v3 stub) ───────────────────────────────────


class CrosswalkCourtlistener(BaseRegistryModel):
    """Links providers to CourtListener dockets.  Not populated in v1.

    verified=True rows must never be overwritten programmatically.
    """

    provider_id: NonEmptyStr
    cl_docket_id: int
    cl_party_id: int | None = None
    match_score: float = Field(ge=0.0, le=1.0)
    match_method: MatchMethod
    verified: bool = False
    reviewer: str | None = None
    reviewed_at: datetime.datetime | None = None
